Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant_Management.Data;
using Restaurant_Management.Models;
using Restaurant_Management.ViewModels;

namespace Restaurant_Management.Controllers;

public class ClientsController : Controller
{
    private readonly PostgresContext _context;
    
    public ClientsController(PostgresContext context)
    {
        _context = context;
    }
    
    public IActionResult Index()
    {
        var clients = _context.Clients.ToList().OrderBy(c => c.Id); 
        return View(clients);
    }
    
    public IActionResult Details(int id)
    {
        var client = _context.Clients.Find(id);
        if (client == null)
        {
            return NotFound();
        }

        return View(client);
    }
    
    public IActionResult Store([Bind("Name,LastNames,Email,Phone")] Client client)
    {

        if (ModelState.IsValid)
        {
            _context.Add(client);
            _context.SaveChanges();
            TempData["message"] = "Cliente agregado con éxito";
            return RedirectToAction(nameof(Index));
        }

        return BadRequest();
    }
    
    /*public IActionResult Edit(int id, /*[Bind("Id,Name,LastNames,Email,Phone")]#1# Client newclient)
    {
        
        var client = _context.Clients.Find(id);
        if (client == null)
        {
            return NotFound();
        }
    
        if (ModelState.IsValid)
        {
            client.Name = newclient.Name;
            client.LastNames = newclient.LastNames;
            client.Email = newclient.Email;
            client.Phone = newclient.Phone;
            _context.SaveChanges();
            TempData["message"] = "El usuario ha sido editado";
        }
        return RedirectToAction(nameof(Index));
    }      */ 

    public IActionResult Edit(Client newclient)
    {
        if (!ModelState.IsValid)
        {
            // Volvemos a la vista con los errores y los datos introducidos
            return View(newclient);
        }

        var client = _context.Clients.Find(newclient.Id);
        if (client == null)
        {
            return NotFound();
        }

        client.Name = newclient.Name;
        client.LastNames = newclient.LastNames;
        client.Email = newclient.Email;
        client.Phone = newclient.Phone;

        _context.SaveChanges();
        TempData["message"] = "El usuario ha sido editado";
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var client = _context.Clients.Find(id);
        if (client == null)
        {
            return NotFound();
        }
        return View(client);
    }
    
    public IActionResult Destroy(int id)
    {
        var client = _context.Clients.Find(id);
        if (client == null)
        {
            return NotFound();
        }

        _context.Clients.Remove(client);
        _context.SaveChanges();
        TempData["message"] = "El usuario ha sido eliminado";
        return RedirectToAction(nameof(Index));
    }
}

Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant_Management.Data;
using Restaurant_Management.Models;
using Restaurant_Management.ViewModels;
namespace Restaurant_Management.Controllers;

public class OrdersController : Controller
{
    private readonly PostgresContext _context;
    
    public OrdersController(PostgresContext context)
    {
        _context = context;
    }
    
    public IActionResult Index()
    {
        // ViewModel
        var viewModel = new OrdersViewModel
        {
            Clients = _context.Clients.ToList(),
            Orders = _context.Orders.ToList()
        };

        return View(viewModel);
    }
    
    public IActionResult Details(int id)
    {
        var order = _context.Orders.Find(id);
        if (order == null)
        {
            return NotFound();
        }

        return View(order);
    }
    
    public IActionResult Store([Bind("OrderNumber,Date,State,fk_ClientID")] Order order)
    {

        if (ModelState.IsValid)
        {
            _context.Add(order);
            _context.SaveChanges();
            TempData["message"] = "Pedido agregado con éxito";
            return RedirectToAction(nameof(Index));
        }

        return BadRequest();
    }
    
    public IActionResult Edit(int id, [Bind("Id,OrderNumber,Date,State,fk_ClientID")] Order NewOrder)
    {
        var order = _context.Orders.Find(id);
        if (order == null)
        {
            return NotFound();
        }
    
        if (ModelState.IsValid)
        {   
            order.OrderNumber = NewOrder.OrderNumber;
            order.Date = NewOrder.Date;
            order.State = NewOrder.State;
            order.fk_ClientID = NewOrder.fk_ClientID;
            _context.SaveChanges();
            TempData["message"] = "La orden ha sido editada";
        }
        return RedirectToAction(nameof(Index));
    }       

    

    [HttpGet]
    public IActionResult Edit(int id)
    {
        ViewBag.Clients = _context.Clients.ToList();
        
        var order = _context.Orders.Find(id);
        if (order == null)
        {
            return NotFound();
        }
        return View(order);
    }
    
    public IActionResult Destroy(int id)
    {
        var order = _context.Orders.Find(id);
        if (order == null)
        {
            return NotFound();
        }

        _context.Orders.Remove(order);
        _context.SaveChanges();
        TempData["message"] = "La orden ha sido eliminada";
        return RedirectToAction(nameof(Index));
    }
}

Controllers/PlatesController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant_Management.Data;
using Restaurant_Management.Models;

namespace Restaurant_Management.Controllers;

public class PlatesController : Controller
{
    private readonly PostgresContext _context;
    
    public PlatesController(PostgresContext context)
    {
        _context = context;
    }
    
    public IActionResult Index()
    {
        // ViewModel
        var plates = _context.Plates.ToList().OrderBy(c => c.Id); 
        return View(plates);
    }
    
    public IActionResult Details(int id)
    {
        var plates = _context.Plates.Find(id);
        if (plates == null)
        {
            return NotFound();
        }

        return View(plates);
    }
    
    public IActionResult Store([Bind("Name,Description,Price,Category")] Plate plate)
    {

        if (ModelState.IsValid)
        {
            _context.Add(plate);
            _context.SaveChanges();
            TempData["message"] = "Plato agregado con éxito";
            return RedirectToAction(nameof(Index));
        }

        return BadRequest();
    }
    
    public IActionResult Edit(int id, [Bind("Id,Name,Description,Price,Category")] Plate newPlate)
    {
        
        var plate = _context.Plates.Find(id);
        if (plate == null)
        {
            return NotFound();
        }
    
        if (ModelState.IsValid)
        {
            plate.Name = newPlate.Name;
            plate.Description = newPlate.Description;
            plate.Price = newPlate.Price;
            plate.Category = newPlate.Category;
            _context.SaveChanges();
            TempData["message"] = "El plato ha sido editado";
        }
        return RedirectToAction(nameof(Index));
    }       

    

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var plate = _context.Plates.Find(id);
        if (plate == null)
        {
            return NotFound();
        }
        return View(plate);
    }
    
    public IActionResult Destroy(int id)
    {
        var plate = _context.Plates.Find(id);
        if (plate == null)
        {
            return NotFound();
        }

        _context.Plates.Remove(plate);
        _context.SaveChanges();
        TempData["message"] = "El plato ha sido eliminado";
        return RedirectToAction(nameof(Index));
    }
}

Controllers/WaitersController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant_Management.Data;
using Restaurant_Management.Models;
namespace Restaurant_Management.Controllers;

public class WaitersController :Controller
{
    private readonly PostgresContext _context;
    
    public WaitersController(PostgresContext context)
    {
        _context = context;
    }
    
    public IActionResult Index()
    {
        // ViewModel
        var waiters = _context.Waiters.ToList().OrderBy(c => c.Id); 
        return View(waiters);
    }
    
    public IActionResult Details(int id)
    {
        var waiter = _context.Waiters.Find(id);
        if (waiter == null)
        {
            return NotFound();
        }

        return View(waiter);
    }
    
    public IActionResult Store([Bind("Name,LastNames,Shift,Experience")] Waiter waiter)
    {

        if (ModelState.IsValid)
        {
            _context.Add(waiter);
            _context.SaveChanges();
            TempData["message"] = "Mesero/a agregado con éxito";
            return RedirectToAction(nameof(Index));
        }

        return BadRequest();
    }
    
    public IActionResult Edit(int id, [Bind("Id,Name,LastNames,Shift,Experience")] Waiter newWaiter)
    {
        
        var waiter = _context.Waiters.Find(id);
        if (waiter == null)
        {
            return NotFound();
        }
    
        if (ModelState.IsValid)
        {
            waiter.Name = newWaiter.Name;
            waiter.LastNames = newWaiter.LastNames;
            waiter.Shift = newWaiter.Shift;
            waiter.Experience = newWaiter.Experience;
            _context.SaveChanges();
            TempData["message"] = "El mesero/a ha sido editado";
        }
        return RedirectToAction(nameof(Index));
    }       

    

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var waiter = _context.Waiters.Find(id);
        if (waiter == null)
        {
            return NotFound();
        }
        return View(waiter);
    }
    
    public IActionResult Destroy(int id)
    {
        var waiter = _context.Waiters.Find(id);
        if (waiter == null)
        {
            return NotFound();
        }

        _context.Waiters.Remove(waiter);
        _context.SaveChanges();
        TempData["message"] = "El mesero/a ha sido eliminado/a";
        return RedirectToAction(nameof(Index));
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurant_Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Restaurant_Management.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ">
            <div class="container-fluid ">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Restaurante</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 d-flex justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Waiters" asp-action="Index">Meseros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plates" asp-action="Index">Platos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Pedidos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Restaurant Management - <a href="https://github.com/JMoralesNunez/sprint-2-activity-1/tree/main" target="_blank">Github</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
    </body>
</html>